# Generated by Django 3.1 on 2020-09-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphAPI', '0002_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel', models.TextField()),
                ('phone', models.TextField()),
                ('date', models.DateField()),
                ('other', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_name', models.TextField()),
                ('ord_address', models.TextField()),
                ('ord_mapid', models.TextField()),
                ('ord_tolprice', models.IntegerField()),
                ('ord_startdate', models.DateField()),
                ('ord_enddate', models.DateField()),
                ('ord_other', models.TextField()),
                ('ord_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='graphAPI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('item_color', models.TextField()),
                ('item_tpye', models.TextField()),
                ('item_size', models.TextField()),
                ('item_salary', models.IntegerField()),
                ('item_time', models.TimeField()),
                ('item_price', models.IntegerField()),
                ('item_amount', models.IntegerField()),
                ('item_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='graphAPI.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.TextField()),
                ('detail_color', models.TextField()),
                ('detail_tpye', models.TextField()),
                ('detail_size', models.TextField()),
                ('detail_price', models.IntegerField()),
                ('detail_amount', models.IntegerField()),
                ('detail_orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitemdetails', to='graphAPI.orderitem')),
            ],
        ),
    ]
